// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsCheck.NUnit")>]
[<assembly: AssemblyProductAttribute("FsCheck.NUnit")>]
[<assembly: AssemblyDescriptionAttribute("Integrates FsCheck with NUnit")>]
[<assembly: AssemblyVersionAttribute("2.7.0")>]
[<assembly: AssemblyFileVersionAttribute("2.7.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsCheck.NUnit"
    let [<Literal>] AssemblyProduct = "FsCheck.NUnit"
    let [<Literal>] AssemblyDescription = "Integrates FsCheck with NUnit"
    let [<Literal>] AssemblyVersion = "2.7.0"
    let [<Literal>] AssemblyFileVersion = "2.7.0"
