// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("FsCheck.Xunit")>]
[<assembly: AssemblyProductAttribute("FsCheck.Xunit")>]
[<assembly: AssemblyDescriptionAttribute("Integrates FsCheck with xUnit.NET")>]
[<assembly: AssemblyVersionAttribute("2.14.0")>]
[<assembly: AssemblyFileVersionAttribute("2.14.0")>]
[<assembly: InternalsVisibleToAttribute("FsCheck.Test")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsCheck.Xunit"
    let [<Literal>] AssemblyProduct = "FsCheck.Xunit"
    let [<Literal>] AssemblyDescription = "Integrates FsCheck with xUnit.NET"
    let [<Literal>] AssemblyVersion = "2.14.0"
    let [<Literal>] AssemblyFileVersion = "2.14.0"
    let [<Literal>] InternalsVisibleTo = "FsCheck.Test"
